# Generated by Django 4.0.6 on 2022-08-06 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='assistants',
        ),
        migrations.RemoveField(
            model_name='course',
            name='helpers',
        ),
        migrations.RemoveField(
            model_name='course',
            name='instructors',
        ),
        migrations.CreateModel(
            name='DingyInstructorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField()),
                ('assigned', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.dingyinstructor')),
            ],
        ),
    ]
