# Generated by Django 4.0.6 on 2022-08-09 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_remove_course_assistants_remove_course_helpers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dingyinstructoravailability',
            name='available',
        ),
    ]
