# Generated by Django 4.0.6 on 2022-08-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_remove_dingyinstructoravailability_note_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistantinstructoravailability',
            old_name='assistant',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='dingyinstructoravailability',
            old_name='instructor',
            new_name='staff',
        ),
    ]
